name: TODO to GitHub Issues

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.10
        with:
          LANGUAGES: "./languages.json"
